version: "3.8"

services:
  bitcoin:
    container_name: bitcoind
    user: 1000:1000
    image: lncm/bitcoind:v25.0
    volumes:
      - ./bitcoin:/data/.bitcoin
      # - /path/to/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
    # command: ["bitcoind", "-conf=/bitcoin/.bitcoin/bitcoin.conf"]
    restart: always
    stop_grace_period: 15m30s
    ports:
      - 8332:8332 # mainnet
      - 8333:8333 # mainnet
      - 8334:8334 # mainnet
      # - 18332:18332 # testnet
      # - 18333:18333 # testnet
      # - 18334:18334 # testnet
      # - 18443:18443 # regtest
      # - 18444:18444 # regtest
      # - 18445:18445 # regtest

    labels:
      - traefik.enable=true
      - traefik.http.routers.bitcoind-service.rule=Host(`${BITCOIN_DOMAIN}`)
      - traefik.http.routers.bitcoind-service.service=bitcoind-service
      - traefik.http.routers.bitcoind-service.entrypoints=web
      - traefik.http.routers.bitcoind-serviceSecure.rule=Host(`${BITCOIN_DOMAIN}`)
      - traefik.http.routers.bitcoind-serviceSecure.service=bitcoind-service
      - traefik.http.routers.bitcoind-serviceSecure.entrypoints=webSecure
      - traefik.http.routers.bitcoind-serviceSecure.tls.certresolver=letsEncrypt

      - traefik.http.middlewares.bitcoind-header.headers.FrameDeny=true
      - traefik.http.middlewares.bitcoind-header.headers.browserXssFilter=true
      - traefik.http.middlewares.bitcoind-header.headers.contentTypeNosniff=true
      - traefik.http.middlewares.bitcoind-header.headers.stsSeconds=315360000
      - traefik.http.middlewares.bitcoind-header.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.bitcoind-header.headers.stsPreload=true

      - traefik.http.middlewares.https-redirect.redirectScheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectScheme.permanent=true

      - traefik.http.routers.bitcoind-service.middlewares=bitcoind-header@docker,https-redirect@docker
      - traefik.http.routers.bitcoind-serviceSecure.middlewares=bitcoind-header@docker,https-redirect@docker

      - traefik.tcp.routers.bitcoind.rule=HostSNI(`*`)
      - traefik.tcp.routers.bitcoind.entrypoints=bitcoind-rpc
      - traefik.tcp.routers.bitcoind.service=bitcoind-svc
      - traefik.tcp.services.bitcoind-svc.loadbalancer.server.port=8332 # mainnet

      # - traefik.tcp.services.bitcoind-service.loadbalancer.server.port=8332 # mainnet
      # - traefik.tcp.services.bitcoind-service.loadbalancer.server.port=18332 # testnet
      # - traefik.tcp.services.bitcoind-service.loadbalancer.server.port=18443 # regtest

networks:
  traefik:
    external: true