version: "3.9"
services:
  bitcoin:
    container_name: bitcoind
    user: "1000:1000"
    image: lncm/bitcoind:v25.0
    volumes:
      # - ./data:/data/.bitcoin
      # - ./bitcoin:/data/.bitcoin
      # - ./bitcoin/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
      - ./data:/data/.bitcoin
      - ./bitcoin:/bitcoin/.bitcoin
    command: ["-conf=/bitcoin/.bitcoin/bitcoin.conf"]
    restart: always
    stop_grace_period: 15m30s
    ports:
      - 8332:8332 # mainnet
      - 8333:8333 # mainnet
      - 8334:8334 # mainnet
      - 18332:18332 # testnet
      - 18333:18333 # testnet
      - 18334:18334 # testnet
      - 18443:18443 # regtest
      - 18444:18444 # regtest
      - 18445:18445 # regtest
      - 28332:28332
      - 28333:28333
    labels:

      - traefik.enable=true
      - traefik.http.routers.bitcoin.rule=Host(`${BITCOIN_DOMAIN}`)
      - traefik.http.routers.bitcoin.service=api@internal
      # - traefik.http.routers.bitcoin.middlewares=auth@file
      - traefik.http.routers.bitcoin.entryPoints=web
      # - traefik.http.routers.bitcoin.middlewares=redirect-to-https

      - traefik.http.routers.bitcoinSecure.rule=Host(`${BITCOIN_DOMAIN}`)
      - traefik.http.routers.bitcoinSecure.service=api@internal
      # - traefik.http.routers.bitcoinSecure.middlewares=auth@file
      - traefik.http.routers.bitcoinSecure.entryPoints=webSecure
      - traefik.http.routers.bitcoinSecure.tls.certResolver=letsEncrypt

      - traefik.http.middlewares.bitcoin-headers.headers.FrameDeny=true
      - traefik.http.middlewares.bitcoin-headers.headers.browserXssFilter=true
      - traefik.http.middlewares.bitcoin-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.bitcoin-headers.headers.stsSeconds=315360000
      - traefik.http.middlewares.bitcoin-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.bitcoin-headers.headers.stsPreload=true


      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true

      #- traefik.tcp.services.bitcoind.loadbalancer.server.port=8332 # mainnet
      # - traefik.tcp.services.bitcoind.loadbalancer.server.port=18332 # testnet
      - traefik.tcp.services.bitcoin.loadbalancer.server.port=18443 # regtest

networks:
  traefik:
    external: true