name: P2P NODE BITCOIN MAINNET to DEV

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    environment:
      name: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Copy files on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.MAIN_DOMAIN }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.DEV_SERVER_KEY }}
          source: docker-compose-dev-02.yaml
          target: /srv/node-bitcoin/
          overwrite: true
          debug: true

      - name: Docker compose up
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /srv/node-bitcoin/
            # touch .htpasswd
            # htpasswd -bB .htpasswd ${{ vars.BASIC_AUTH_USER }} ${{ secrets.BASIC_AUTH_PASSWORD }}
            export BITCOIN_DOMAIN=${{ vars.BITCOIN_DOMAIN }}
            docker compose -f docker-compose-dev-02.yaml pull
            docker compose -f docker-compose-dev-02.yaml down --verbose
            docker compose -f docker-compose-dev-02.yaml up -d --remove-orphans
          host: ${{ vars.MAIN_DOMAIN }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.DEV_SERVER_KEY }}
